[project]
name = "planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chromadb>=1.0.20",
    "sentence-transformers>=5.1.0",
    "typer>=0.17.4",
    "openai>=1.0.0",
]
